/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@aws-0-eu-central-1.pooler.supabase.com:5432/postgres -t papers_with_code_tasks -s public
 *
 */


export type Json = unknown;

// Table papers_with_code_tasks
export interface PapersWithCodeTasks {
  url: string;
  count: number;
  updated_at: Date | null;
}
export interface PapersWithCodeTasksInput {
  url: string;
  count?: number;
  updated_at?: Date | null;
}
const papers_with_code_tasks = {
  tableName: 'papers_with_code_tasks',
  columns: ['url', 'count', 'updated_at'],
  requiredForInsert: ['url'],
  primaryKey: 'url',
  foreignKeys: {},
  $type: null as unknown as PapersWithCodeTasks,
  $input: null as unknown as PapersWithCodeTasksInput
} as const;


export interface TableTypes {
  papers_with_code_tasks: {
    select: PapersWithCodeTasks;
    input: PapersWithCodeTasksInput;
  };
}

export const tables = {
  papers_with_code_tasks,
}
